// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB45-EpLQxIeMdjImzp4ISjDp0aLrBvsg',
    appId: '1:29758240123:web:9a694535bb25f7636bb9de',
    messagingSenderId: '29758240123',
    projectId: 'seguimiento-credito',
    authDomain: 'seguimiento-credito.firebaseapp.com',
    storageBucket: 'seguimiento-credito.firebasestorage.app',
    measurementId: 'G-JX4DT86108',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRRFZA0-SYQH8g2jb-Baxk12aMKZgaec',
    appId: '1:29758240123:android:35abaae6e64506346bb9de',
    messagingSenderId: '29758240123',
    projectId: 'seguimiento-credito',
    storageBucket: 'seguimiento-credito.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5FMjd_CVX5_6oGqw1o_XogNgkjLrfC8',
    appId: '1:29758240123:ios:01f873f1934f920d6bb9de',
    messagingSenderId: '29758240123',
    projectId: 'seguimiento-credito',
    storageBucket: 'seguimiento-credito.firebasestorage.app',
    iosBundleId: 'com.example.seguimientoCredito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt5FMjd_CVX5_6oGqw1o_XogNgkjLrfC8',
    appId: '1:29758240123:ios:01f873f1934f920d6bb9de',
    messagingSenderId: '29758240123',
    projectId: 'seguimiento-credito',
    storageBucket: 'seguimiento-credito.firebasestorage.app',
    iosBundleId: 'com.example.seguimientoCredito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB45-EpLQxIeMdjImzp4ISjDp0aLrBvsg',
    appId: '1:29758240123:web:fcfb8b7c9f8f86356bb9de',
    messagingSenderId: '29758240123',
    projectId: 'seguimiento-credito',
    authDomain: 'seguimiento-credito.firebaseapp.com',
    storageBucket: 'seguimiento-credito.firebasestorage.app',
    measurementId: 'G-HH9NSV4PPR',
  );

}